#eureka:
#  client:
#    healthcheck:
#      enabled: true
#    service-url:
#      default-zone: http://localhost:1111/eureka/
#  instance:
#    status-page-url-path: /info
#    health-check-url-path: /health
spring:
  application:
    name: task-app
  cache:
    ehcache:
      config: classpath:ehcache.xml
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    #prefix: classpath:/templates/


eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/



# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port
